export const projects = [
  {
    id: 1,
    title: 'KenzieHub',
    img: 'https://i.imgur.com/BMOqmxH.png',
    demo: 'https://kenzie-hub-letlm.vercel.app/',
    repo: 'https://github.com/letlm/kenziehub-REACT',
    level: 'front-end',
    tags: '#reactjs, #apirest, #crud, #styled-components',
    description:
      'Consumindo uma API, o usuário pode criar uma conta, fazer login e cadastrar tecnologias que estudou/está estudando. Ainda é possível editar o nível de estudos da tecnologia ou/e excluí-las.',
  },
  {
    id: 2,
    title: 'NuKenzie',
    img: 'https://i.imgur.com/Rkxulnx.png',
    demo: 'https://nu-kenzie-letlm.vercel.app/',
    repo: 'https://github.com/letlm/nukenzie-REACT',
    level: 'front-end',
    tags: '#reactjs, #css3, #crud',
    description:
      'Gerenciador de gastos no qual é possível cadastrar entradas e despesas, além de possuir a funcionalidade de filtrar os cadastros bem como excluí-los.',
  },

  {
    id: 3,
    title: 'BurguerKenzie',
    img: 'https://i.imgur.com/5vrQjVV.png',
    demo: 'https://kenzie-burguer-letlm.vercel.app/',
    level: 'front-end',
    tags: '#reactjs, #apirest, #css3',
    repo: 'https://github.com/letlm/kenzieBurguer-REACT',
    description:
      'Simulando uma hamburgueria, é possível adicionar apenas uma unidade de cada produto. É apresentado o valor total do carrinho, sendo possível remover os produtos dele.',
  },
  {
    id: 4,
    title: 'KMDB',
    img: 'https://i.imgur.com/xOEdmGH.png',
    demo: 'https://github.com/letlm/kmdb-python',
    level: 'back-end',
    tags: '#python, #django, #djangorestframework',
    repo: 'https://github.com/letlm/kmdb-python',
    description: 'Aplicação para gerenciar usuários, filmes e reviews',
  },
  {
    id: 5,
    title: 'Kenzie Pet',
    img: 'https://i.imgur.com/cKAtw9j.png',
    demo: 'https://github.com/letlm/kenzie-pet-python',
    level: 'back-end',
    tags: '#python, #django, #djangorestframework, #api',
    repo: 'https://github.com/letlm/kenzie-pet-python',
    description:
      'Aplicação simples para ajudar donos de PetShop a guardar dados de animais',
  },
  {
    id: 6,
    title: 'Kontent',
    img: 'https://i.imgur.com/GREA4Gi.png',
    demo: 'https://github.com/letlm/kontent-python',
    level: 'back-end',
    tags: '#python, #crud, #djangorestframework',
    repo: 'https://github.com/letlm/kontent-python',
    description: 'CRUD de gerenciamento de conteúdos',
  },

  {
    id: 7,
    title: 'KenzieShop - Context Api',
    img: 'https://i.imgur.com/z9xMyqt.png',
    demo: 'https://kenzieshop-contextapi-letlm.vercel.app/',
    repo: 'https://github.com/letlm/kenzieshop-contextAPI',
    level: 'front-end',
    tags: '#reactjs, #contextApi #styled-components',
    description:
      'Simulação de ecommerce feita com context Api. O usuário pode adicionar produtos no carrinho e removê-los, além de simular uma compra.',
  },
  {
    id: 8,
    title: 'KenzieShop - Redux',
    img: 'https://i.imgur.com/kUlUnOa.png',
    demo: 'https://kenzie-shop-redux-letlm.vercel.app/',
    repo: 'https://github.com/letlm/kenzieshop-REDUX',
    level: 'front-end',
    tags: '#reactjs, #redux, #styled-components, #redux-thunk',
    description:
      'Simulação de ecommerce feita com redux, utilizando o redux-thunk para que os produtos adicionados permaneçam no carrinho e sejam removidos apenas pelo usuário.',
  },
  {
    id: 9,
    title: 'BeraTop - EM GRUPO',
    img: 'https://i.imgur.com/DCnr2v9.png',
    demo: 'https://capstone-bera-top.vercel.app/',
    repo: 'https://github.com/letlm/capstone-bera-top',
    level: 'front-end',
    tags: '#reactjs, #apirest, #crud',
    description:
      'Reune diversas marcas de cervejas no qual o usuário pode criar uma conta e deixar sua avaliação e preço sobre as cervejas, além de poder visualizar avaliações de outros usuários.',
  },
  {
    id: 10,
    title: 'CRUD (TypeORM + PostgreSQL)',
    img: 'https://i.imgur.com/b1zHXor.png',
    demo: 'https://github.com/letlm/crud-typeorm-postgresql',
    level: 'back-end',
    tags: '#typescript, #crud, #expressjs #typeorm, #postgresql',
    repo: 'https://github.com/letlm/crud-typeorm-postgresql',
    description:
      'Serviço de back-end responsável por gerenciar um CRUD de usuário utilizando TypeORM.',
  },
  {
    id: 11,
    title: 'Produtos e categorias',
    img: 'https://i.imgur.com/C0yxVrE.png',
    demo: 'https://github.com/letlm/produtos-e-categorias',
    level: 'back-end',
    tags: '#javascript, #crud',
    repo: 'https://github.com/letlm/produtos-e-categorias',
    description:
      'Serviço de back-end responsável por gerenciar produtos e suas categorias.',
  },
  {
    id: 12,
    title: 'Cadastro de clientes',
    img: 'https://i.imgur.com/ScleIWH.png',
    demo: 'https://github.com/letlm/crud-back-end-kenzie',
    level: 'back-end',
    tags: '#typescript, #crud, #typeorm',
    repo: 'https://github.com/letlm/crud-back-end-kenzie',
    description:
      'Serviço de back-end responsável por gerenciar cadastros de clientes',
  },

  {
    id: 13,
    title: 'Portfólio',
    img: 'https://i.imgur.com/xbbdnOR.png',
    demo: 'https://portfolio-letlm.vercel.app/',
    repo: 'https://github.com/letlm/portfolio',
    level: 'front-end',
    tags: '#reactjs, #javascript',
    description: 'Portfólio inicial criado com React JS',
  },
  {
    id: 14,
    title: 'Portfólio 2.0',
    img: 'https://i.imgur.com/Uh8pHof.png',
    demo: 'https://letlm.vercel.app/',
    repo: 'https://github.com/letlm/portfolio-let',
    level: 'front-end',
    tags: '#next.js, #typescript',
    description: 'Portfólio versão 2.0 criado com NextJS e Typescript',
  },
  {
    id: 15,
    title: 'Formulário de Cadastro',
    img: 'https://i.imgur.com/92h3EkY.png',
    demo: 'https://formulario-de-cadastro-letlm.vercel.app/',
    repo: 'https://github.com/letlm/formulario-de-cadastro-REACT',
    level: 'front-end',
    tags: '#reactjs, #reacthooks',
    description:
      'Formulário de cadastro utilizando as bibliotecas: React Hook Form, Yup e React Router Dom.',
  },

  {
    id: 16,
    title: 'Selector Hat',
    img: 'https://i.imgur.com/jfyPE6q.png',
    demo: 'https://selector-hat-letlm.vercel.app/',
    repo: 'https://www.google.com.br/',
    level: 'front-end',
    tags: '#html5, #css3, #javascript, #poo',
    description:
      "Inspirado na 'Magic 8-ball' mas com uma pegada no universo Harry Potter. Foi realizado com Programação Orientada a Objetos(POO). O usuário digita uma pergunta e o Selector Hat responderá!",
  },

  {
    id: 17,
    title: 'Blog M2',
    img: 'https://i.imgur.com/wj4HHlo.png',
    demo: 'https://psychic-invention-165e1ac8.pages.github.io/',
    repo: 'https://github.com/letlm/blog-JS',
    level: 'front-end',
    tags: '#javascript, #css3, #dom',

    description:
      'Fazendo o consumo de uma API, é possível fazer o cadastro e login do usuário. Após logado, é possível fazer posts no blog, excluir ou editar os próprios posts e ainda ler os posts de outros usuários.',
  },
  {
    id: 18,
    title: 'Quadro de Medalhas',
    img: 'https://i.imgur.com/D9yd8cq.png',
    demo: 'https://quadro-de-medalhas.vercel.app/',
    repo: 'https://github.com/letlm/quadro-de-medalhas-JS',
    level: 'front-end',
    tags: '#javascript, #css3, #dom',
    description:
      'Quadro que exibe a quantidade de medalhas dos 15 países que mais tiveram vitórias nas competições das Olimpíadas. Para obter os dados foi utilizada uma api e para contruir a tabela o DOM.',
  },
  {
    id: 19,
    title: 'Lista de Produtos',
    img: 'https://i.imgur.com/WIKnQ0T.png',
    demo: 'https://lista-de-produtos-letlm.vercel.app/',
    repo: 'https://github.com/letlm/lista-de-produtos-JS',
    level: 'front-end',
    tags: ' #javascript, #css3',
    description:
      "Aplicação simulando um 'supermercado', sendo possível adicionar os produtos no carrinho, bem como é possível fazer a busca por nome ou categoria.",
  },
  {
    id: 20,
    title: 'Contador de Frequência',
    img: 'https://i.imgur.com/UF2mhax.png',
    demo: 'https://contador-de-frequencia.vercel.app/',
    repo: 'https://github.com/letlm/contador-de-frequencia-JS',
    level: 'front-end',
    tags: ' #html5, #css3, #javascript',
    description:
      'A aplicação registra a frequência de cada uma das letras e palavras usadas em um determinado texto/palavra que o usuário digitar.',
  },
  {
    id: 21,
    title: 'Rolando Dados',
    img: 'https://i.imgur.com/pW1iwDg.png',
    demo: 'https://rolando-dados.vercel.app/',
    repo: 'https://github.com/letlm/rolando-dados-JS',
    level: 'front-end',
    tags: ' #html5, #css3, #javascript',
    description:
      'A aplicação simula a rolagem de dois dados várias vezes, no qual é registrado a frequência de cada resultado e ainda é encontrado um gráfico com as frequências obtidas.',
  },
  {
    id: 22,
    title: 'KenzieFlix',
    img: 'https://i.imgur.com/4qbofIP.png',
    demo: 'https://kenzieflix-letlm.vercel.app/',
    repo: 'https://github.com/letlm/kenzieflix-CSS',
    level: 'front-end',
    tags: '#css3',
    description:
      'O objetivo era a estilização de um layout de uma plataforma de streaming utilizando CSS com conceitos de flex-box. O código HTML já estava pronto, ou seja, não foi feito por mim. Realizei apenas a estilização.',
  },
  {
    id: 23,
    title: 'Menu Restaurante',
    img: 'https://i.imgur.com/nOtBS6T.png',
    demo: 'https://menu-restaurante.vercel.app/',
    repo: 'https://github.com/letlm/menu-restaurante-CSS',
    level: 'front-end',
    tags: '#css3',
    description:
      'O objetivo era apenas a estilização de um Menu de Restaurante de duas formas diferentes utilizando CSS. O código HTML já estava pronto, ou seja, não foi feito por mim. Realizei apenas a estilização.',
  },
];
